### ISSUE TITLE
Pls make us save houses not from us

### ISSUE THREAD

**Issue by Kumicoo** [Bluefissure/HousingPos#16]
Can you please make so it saves house even if not owned? Its hard to copy some furnishings.

**Comment by Kumicoo** [comment]
it is possible to read furnishing and position from houses you dont own btw, i just need option to export that list and apply bdth.

**Comment by Bluefissure** [comment]
It's technically possible but I won't do that in my plugin. Some furniture layouts are made by players that care about their design and I don't want to raise any drama.
