### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by Vatta14861** [Bluefissure/HousingPos#17]
when will it be updated?

**Comment by Bluefissure** [comment]
Already updated

**Comment by Vatta14861** [comment]
it says on the Dalamud plugin installer that it is outdated and incompatible at the moment. please wait for it to be updated by its author.

**Comment by Bluefissure** [comment]
please follow https://github.com/Bluefissure/DalamudPlugins/blob/Bluefissure/README.md to install

**Comment by Vatta14861** [comment]
thank you, I deleted and reinstalled <3
