### ISSUE TITLE
Don't force culture

### ISSUE THREAD

**Issue by anna-is-cute** [Bluefissure/HousingPos#4]
Changing the culture the way HousingPos does affects *all* plugins and leads to confusing bugs. Culture-aware methods using the Invariant culture can be used instead.

**Comment by Bluefissure** [comment]
Thanks! Will push a fix tomorrow!

**Comment by Bluefissure** [comment]
Thanks, I removed the force culture in https://github.com/Bluefissure/HousingPos/commit/00d8e9f70a1b33983ebe330cc8bde924a03d7943.
It seems the parsing error from culture only happens when communicating with bdth so I only add Invariant culture there.
