### ISSUE TITLE
Question about api4

### ISSUE THREAD

**Issue by Kyfii** [Bluefissure/HousingPos#7]
Hi! Sorry for bothering you, but is there any chance this gets updated to api4 at any point in the future?

**Comment by Bluefissure** [comment]
I was busy dealing with Dalamud upgrading for CN and DelvUI stuff yesterday so it may be late this week.

**Comment by Kyfii** [comment]
Hey! Thanks for answering! There's no rush at all, I was just wondering if you had any plans on updating it at all! Please take your time! And again, thank you for taking the time to answer!!

**Comment by Bluefissure** [comment]
> Hey! Thanks for answering! There's no rush at all, I was just wondering if you had any plans on updating it at all! Please take your time! And again, thank you for taking the time to answer!!

Sure, my third-party plugins for api4 will be released in another branch of the same repo [here](https://github.com/Bluefissure/DalamudPlugins/tree/Bluefissure-api4).

The **Inviter** and **DoubleWeaver** are already upgraded and released there.

**Comment by Kyfii** [comment]
> > Hey! Thanks for answering! There's no rush at all, I was just wondering if you had any plans on updating it at all! Please take your time! And again, thank you for taking the time to answer!!
> 
> Sure, my third-party plugins for api4 will be released in another branch of the same repo [here](https://github.com/Bluefissure/DalamudPlugins/tree/Bluefissure-api4).
> 
> The **Inviter** and **DoubleWeaver** are already upgraded and released there.


Awesome, thank you so much!! <3

**Comment by Bluefissure** [comment]
It's already upgraded.

You can re-open or create another issue if you run into any problems using the api4 HousingPos.

**Comment by ItsCinnabar** [comment]
> It's already upgraded.
> 
> You can re-open or create another issue if you run into any problems using the api4 HousingPos.

Hi Bluefissure,

XIVLauncher tells me that this plugin is out of date and incompatible at the moment. It didn't let me update it. When I tried to delete it to reinstall, nothing appears in a search for new plugins. I do have the repository added still.

**Comment by Bluefissure** [comment]
> > It's already upgraded.
> > You can re-open or create another issue if you run into any problems using the api4 HousingPos.
> 
> Hi Bluefissure,
> 
> XIVLauncher tells me that this plugin is out of date and incompatible at the moment. It didn't let me update it. When I tried to delete it to reinstall, nothing appears in a search for new plugins. I do have the repository added still.

Delete the old third-party repo and add [Bluefissure-api4](https://github.com/Bluefissure/DalamudPlugins/tree/Bluefissure-api4).
